### ISSUE TITLE
HF - Login

### ISSUE THREAD

**Issue by JSnow11** [gii-is-DP1/dp1-2020-g1-08#66]
### ToDo
- [x] Submit button color transition

- [x] Validation delay

- [x] Avoid movements while showing error msgs

- [x] Sign up button

- [x] Validation overwrite

- [x] User not found error CSS

**Comment by JSnow11** [comment]
@IgnacioNavarro Te dejo el tema de CSS de la transición de colores y a ver si consigues que no se mueva todo cuando salta un error de validación en el form.

**Comment by JSnow11** [comment]
Ahora que hemos estado integrando con el back para hacer la petición de login he añadido un **mensaje de usuario no registrado**, habría que meterle css y ponerlo debajo del botón de login centrado o donde quede mejor. Te lo dejo a ti @IgnacioNavarro

**Comment by JSnow11** [comment]
También te quería comentar que si puedes unas más los inputs y los mensajes de error, veo demasiado espacio entre ellos, pero si tu lo ves bien así para alante. @IgnacioNavarro
